language: python
python: 3.7
dist: xenial
sudo: true

cache:
  directories:
  - "$HOME/Library/Caches/Homebrew"
env:
  global:
  - MUPDF='https://mupdf.com/downloads/archive/mupdf-1.14.0-source.tar.gz'
  - COPYFILE_DISABLE=1
matrix:
  include:
  - os: linux
    sudo: required
    python: '3.7'
    services:
    - docker
    env: PIP=pip
    before_script:
    - export CIBW_BEFORE_BUILD="yum install -y zlib-devel && cd mupdf && make HAVE_X11=no
      HAVE_GLFW=no HAVE_GLUT=no prefix=/usr/local install && cd .."
    - export CIBW_ENVIRONMENT='CFLAGS="-fPIC -std=gnu99"'
  - os: osx
    osx_image: xcode8.3
    language: generic
    services:
    - docker
    env: PIP=pip3
    before_install:
    - brew update -q
    - brew outdated python || brew upgrade python
    - sudo mkdir -p /usr/local/man && sudo chmod a+rw /usr/local/man
    before_script:
    - export CIBW_BEFORE_BUILD="cd mupdf && make HAVE_X11=no HAVE_GLFW=no HAVE_GLUT=no
      prefix=/usr/local install && cd .."
    - export CIBW_ENVIRONMENT='CFLAGS=-fPIC'
install:
- "$PIP install cibuildwheel==0.10.0"
- mkdir mupdf && wget -q $MUPDF -O - | tar zx -C mupdf --strip-components=1
- cp fitz/_mupdf_config.h mupdf/include/mupdf/fitz/config.h
script:
- export CIBW_SKIP="cp33-* *i686"
- export CIBW_TEST_COMMAND="python -c 'import fitz'"
- cibuildwheel --output-dir wheelhouse

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  keep-history: false
  skip_cleanup: true
  local-dir: wheelhouse
  repo: JorjMcKie/PyMuPDF-wheels
  target-branch: $TRAVIS_OS_NAME
  on:
    repo: JorjMcKie/py-mupdf
