name: Test quick

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  test_quick:
    name: Test quick
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We test on just Ubuntu with MuPDF master.
        #
        os: [ubuntu-latest]

      # Avoid cancelling of all cibuildwheel runs after a single failure.
      fail-fast: false

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2

      - name: test_quick

        env:
            inputs_PYMUPDF_SETUP_MUPDF_BUILD: "git:--recursive --depth 1 --shallow-submodules --branch master https://github.com/ArtifexSoftware/mupdf.git"
            inputs_flavours: "0"
            inputs_sdist: "0"
            inputs_wheels_cps: "cp312*"
            inputs_wheels_default: "0"
            inputs_wheels_linux_auto: "1"
            inputs_wheels_macos_auto: "1"
            inputs_wheels_windows_auto: "1"
        run:
          python scripts/gh_release.py


  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .codespell-ignorewords
          exclude_file: .codespell-ignorelines
          check_filenames: true
          check_hidden: true
          skip: "*.pdf,src_classic,locales,prism.js,tests"
          # if we don't fix everything we can set this
          # only_warn: 1
