name: Test mupdf master branch

on:
  schedule:
    - cron: '13 6 * * *'
  workflow_dispatch:

jobs:

  test_mupdf_master_branch:
    # Build+test current PyMuPDF git with mupdf git master branch.
    #
    name: Test mupdf master branch
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]

      # Avoid cancelling of all cibuildwheel runs after a single failure.
      fail-fast: false

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: test_mupdf-master-branch
        env:
            inputs_PYMUPDF_SETUP_MUPDF_BUILD: "git:--recursive --depth 1 --shallow-submodules --branch master https://github.com/ArtifexSoftware/mupdf.git"
            inputs_flavours: "0"
            inputs_sdist: "0"
            inputs_wheels_cps: "cp312*"
            inputs_wheels_default: "0"
            inputs_wheels_linux_auto: "1"
            inputs_wheels_macos_auto: "1"
            inputs_wheels_windows_auto: "1"
        run:
          python scripts/gh_release.py
